### ISSUE TITLE
Issue installing `skott@0.32.1` with pnpm

### ISSUE THREAD

**Issue by jgoux** [antoine-coulon/skott#141]
## Summary

I can't install `skott@0.32.1` with pnpm, it seems that it is now depending on `skott-webapp@^2.1.1` but this version doesn't exist which makes pnpm unhappy:

```
 ERR_PNPM_NO_MATCHING_VERSION  No matching version found for skott-webapp@^2.1.1

This error happened while installing the dependencies of skott@0.32.1

The latest release of skott-webapp is "2.1.0".

If you need the full list of all 15 published versions run "$ pnpm view skott-webapp versions".
```

It seems that you publish Github Action failed half way: https://github.com/antoine-coulon/skott/actions/runs/7716115674/job/21032188649#step:8:63 😅 

## Reproduction steps

```sh
pnpm install skott@0.32.1
```

  **Expected result:** 

  **Actual result:** 

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `skott` installed version? |  |
| Operating system? |  |
| Would you consider contributing a PR? |  |
| Node.js version (`node -v`)? |  |

**Comment by antoine-coulon** [comment]
Hello @jgoux thanks for the heads up.

I just restarted the CI job and it should have fixed it but publishing the missing packages.

It seems that the release CI job failed for some reason and because changesets does not do atomic releases, dependents packages of skott (webapp and fs-tree-structure) were not published after skott's was published with its manifest updated.

I'll try to see how we could prevent that weird case from happening when multiple monorepo packages are published at once. 

Thanks for reporting the issue!
