### ISSUE TITLE
UX - Webapp display - search is difficult

### ISSUE THREAD

**Issue by bam-charlesbo** [antoine-coulon/skott#18]
I really like your tool,

Therefore I am making suggestions to see it evolve.

Once the graph is displayed, like this :
![Capture d’écran 2022-12-19 à 18 02 15](https://user-images.githubusercontent.com/108009537/208480013-a35cb816-65e5-4f7e-8f69-ac64a950f2bd.png)

It would be great to add these features :
- underline the specified file as parameter
- - with command for example `skott src/pages/PaymentPage/PaymentPage.component.tsx`, I would like to see the item `PaymentPage.component.tsx` highlighted
- allow browser text search (cmd + F)
- - OR create your own search and highlight searched item

By the way I would be pleased to help you on this.

Let me know if you find my suggestions useful,

You can contact me on : charlesbo@bam.tech

**Comment by antoine-coulon** [comment]
@bam-charlesbo 

Thanks to you for providing some feedback!

You're completely right, I have been personally using the tool on the enterprise projects I'm working on and it's true that the visualisation is clearly not ideal for a real-world graph. Searching specific components is very tedious at the moment, so there is clearly room for improvement :)

To be honest, I targeted a minimalist UI for the first release including this new display mode (just got out recently).

It turns out that the "custom search" you suggested is something that I planned to add in the next versions of the app, so I'm very happy to see that we both consider that feature useful.

For the entry point highlight, nice one, I didn't even think about that, it's indeed a great idea!

I would be pleased if you could initiate some work on it!

Feel free to land some PRs and open discussions directly here on GitHub (I'm not really active elsewhere unfortunately), it will also enhance the visibility of the work in progress for everyone coming here and avoiding duplicate issues/feature requests

**Comment by antoine-coulon** [comment]
A new version of `skott` **(v0.14.1)** and `skott-webapp` just came out including the features mentioned in #25. I'm closing this one but feel free to open another issue to suggest other enhancements.
