### ISSUE TITLE
Error in Jest Environment

### ISSUE THREAD

**Issue by Steflb20** [antoine-coulon/skott#75]
I was trying to use skott in a jest environment in order to create a unit test that scans my directories for circular dependencies, but I came across the following error:

```
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import * as O from "@effect/data/Option";
```

This issue is probably caused by the usage of ECMAScript Modules in skott. Is there a chance of backward compatibility being implemented into skott, so there won't be any issues like that with other libraries as well?

**Comment by antoine-coulon** [comment]
Hello @Steflb20, what a great idea to leverage unit tests to check that 🙂

There is no on-going work to make skott able to ship dual ESM/CJS but this is something I can do to make the transition smoother. Until now people have been mostly using skott through the CLI so CJS/ESM was not a thing but for the API it would be more convenient. 

While waiting for the dual ESM/CJS publish, because Jest unfortunately does not support ECMAScript modules out of the box, what you could do is run Jest using the Node.js `--experimental-vm-modules` flag that[ enables an experimental support for ESM](https://jestjs.io/docs/ecmascript-modules). Using that you can either using ESM's module imports (`import`) or use dynamic imports for importing skott e.g. `const { default: skott } = await import("skott");` while keeping `require` for other module imports.

I'm currently on vacation so there is no chance that this will be done by the end of the month. Nevertheless, I just [created an issue on that subject](https://github.com/antoine-coulon/skott/issues/76) #76 to make it possible asap.

**Comment by antoine-coulon** [comment]
Hello @Steflb20, sorry for the delay and response time.

I was initially open to do a dual publish to improve DX and to expand the use of skott, thing that would fix the problem that you're having with Jest. Nevertheless during the last few months, I've been witnessing lot of struggle with CJS/ESM dual shit and actually I've been living it myself.  I'm usually a fervent defender of ESM only, as it undeniably tends to be the only module system. Also recently, some popular tools like TypeScript are doubling efforts to promote ESM.

I don't want to be part -at my own tiny scale- of the movement that slows down the change and keeps publishing dual CJS/ESM while they don't really have legacy users running on CJS. I think we should go forward, pick one module system and stick with it.

Unfortunately for project like Jest that still don't support ESM after all these years, I'd say it's sad but it's their problem and this should be fixed upstream. Modern alternatives like Node.js builtin runner or Vitest support ESM natively.

Consequently, I will close both issues related to this subject, #76 #75.

Thanks again for taking time to open this issue.
