### ISSUE TITLE
Disable graph out when using Skott as a command line tool

### ISSUE THREAD

**Issue by AlexMachin1997** [antoine-coulon/skott#99]
Hi everyone,

I'm not logging an issue this is more a general question about the usage of Skott.

So I'm looking at switching from Madge to Skott as it comes with a lot more out of the box and has a better api, however, I have noticed that when using Skott it outputs a visual graph whether that is via the web app or some external file.

I'm wanting to use Skott purely as a command line tool, Is it possible to disable the visual output and instead just have some basic information outputted to the console e.g. if I have a circular dependency show me information about that.

Any feedback and comments are appreciated.

Thank's,

Alex

**Comment by antoine-coulon** [comment]
Hey @AlexMachin1997, welcome aboard!

I'm not sure to understand what do you exactly mean with "visual graph" but with skott you have many ways to exploit the graph itself without any visualization involved, whether it's from the CLI or from the JavaScript API.

If you're willing to use skott from the CLI but don't want to display the graph itself you can provide the `raw` display mode which basically skips any form of visual rendering of the generated graph.

```bash
skott --displayMode=raw
```

If you then want to combine that with the display of the circular dependencies:

```bash
skott --displayMode=raw --showCircularDependencies
```

Note that you can use flag aliases if you want to shorten the CLI command:

```bash
skott -m raw -s
```

Aliases (short flags) were reworked recently by @ACHP in **0.29.0**, they now work as expected. You can exec `skott --help` to see more :) 

By the way I'm re-opening the issue if you still have questions (I don't know if you closed it voluntarily because you found answers on the documentation). Let me know!
